'use strict';
(() => {
  const data = window.DASHBOARD_DATA;
  const state = {view:'visao',range:30,format:'todos',chartMetric:'reach',query:'',theme:'todos',sort:'date',direction:-1,page:0,compare:true};
  const $ = selector => document.querySelector(selector);
  const nf = new Intl.NumberFormat('pt-BR');
  const num = n => n == null ? '—' : nf.format(Math.round(n));
  const compact = n => n == null ? '—' : n >= 1e6 ? `${(n/1e6).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi` : n>=1000 ? `${(n/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})} mil` : num(n);
  const pct = n => n == null ? '—' : `${n.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
  const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shortDate = date => new Date(date.slice(0,10)+'T12:00:00Z').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',timeZone:'UTC'});
  const fullDate = date => new Date(date.slice(0,10)+'T12:00:00Z').toLocaleDateString('pt-BR',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
  const sum = (rows,key) => rows.reduce((v,row)=>v+(row[key]??0),0);
  const mean = values => values.length ? values.reduce((a,b)=>a+b,0)/values.length : 0;
  const median = values => {const s=values.filter(Number.isFinite).sort((a,b)=>a-b);return s.length ? (s[Math.floor((s.length-1)/2)]+s[Math.ceil((s.length-1)/2)])/2 : null;};
  const formats={reel:'Reels',imagem:'Imagens',carrossel:'Carrosséis'};
  const colors={reel:'#ff653b',imagem:'#7e97db',carrossel:'#c3cb78'};
  const views = {
    visao:{title:'Visão geral',eyebrow:'DESEMPENHO DO PERFIL',subtitle:'Alcance, crescimento e eficiência em uma única leitura.'},
    diario:{title:'Diário',subtitle:'A evolução da conta, um dia de cada vez.'},
    conversao:{title:'Conversão',subtitle:'O caminho entre descobrir o conteúdo e começar a seguir.'},
    vida:{title:'Vida do post',subtitle:'Resultados na mesma idade de publicação.'},
    conteudo:{title:'Conteúdo',subtitle:'Formatos, frequência e resultados por publicação.'},
    reels:{title:'Reels',subtitle:'Tempo assistido, duração e comportamento da audiência.'},
    temas:{title:'Temas',subtitle:'Como cada linha editorial aparece nos resultados.'},
    publico:{title:'Público',subtitle:'Um exemplo de quem compõe a comunidade do perfil.'},
    analise:{title:'Análise',subtitle:'Leituras do exemplo para planejar o próximo conteúdo.'},
    benchmark:{title:'Benchmark',subtitle:'Compare resultados usando a mesma fórmula e uma fonte validada.'},
    posts:{title:'Posts',subtitle:'Explore, compare e exporte as publicações do período.'},
    dados:{title:'Origem e cobertura',subtitle:'Fontes, campos disponíveis e fórmulas de cada análise.'}
  };
  const days = () => data.daily.slice(-state.range);
  const previousDays = () => data.daily.slice(-state.range*2,-state.range);
  const periodPosts = () => data.posts.filter(p=>p.date>=days()[0].date&&p.date<=days().at(-1).date&&(state.format==='todos'||p.format===state.format));
  const signed = n => `${n>0?'+':''}${num(n)}`;
  const rate = (a,b,m=100) => Number.isFinite(a)&&b>0 ? a/b*m : null;
  const quartile = (values,q) => {const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*q,lo=Math.floor(i);return a[lo]+(a[Math.ceil(i)]-a[lo])*(i-lo);};
  const snapshot = (p,age=7) => p.snapshots.find(s=>s.ageDays===age);
  const perThousand = (p,key) => rate(p[key],p.reach,1000);
  const decimal = n => n==null?'—':n.toLocaleString('pt-BR',{maximumFractionDigits:1});
  const postLink = p => `<button class="post-title-button" data-post="${p.id}">${esc(p.title)}</button>`;
  const growth = rows => sum(rows,'followersGained')-sum(rows,'followersLost');
  function delta(current,previous){if(!state.compare)return '<span class="delta neutral">comparação oculta</span>';if(!Number.isFinite(previous)||previous===0)return '<span class="delta neutral">sem base</span>';const v=(current-previous)/Math.abs(previous)*100;return `<span class="delta ${v<0?'negative':''}">${v>=0?'+':''}${pct(v)}</span>`;}
  function spark(values,color='#ff653b'){const hi=Math.max(...values,1),lo=Math.min(...values),diff=hi-lo||1;return `<svg class="mini-chart" viewBox="0 0 240 32" preserveAspectRatio="none" aria-hidden="true"><path d="${values.map((v,i)=>`${i?'L':'M'}${i/(values.length-1||1)*240},${29-(v-lo)/diff*24}`).join(' ')}" fill="none" stroke="${color}" stroke-width="1.7" vector-effect="non-scaling-stroke"/></svg>`;}
  function kpi(label,value,current,previous,symbol,values,explainer=''){return `<article class="card kpi ${label==='Saldo de seguidores'?'highlight':''}"><div class="kpi-title">${label}<span class="kpi-symbol" aria-hidden="true">${symbol}</span></div><div class="kpi-number">${value}</div><div class="kpi-bottom">${delta(current,previous)}<span>${state.compare?`vs. ${state.range} dias anteriores`:''}</span></div>${explainer?`<p class="kpi-explainer">${explainer}</p>`:''}${spark(values)}</article>`;}
  function heading(title,subtitle,extra=''){return `<div class="card-heading"><div><h3>${title}</h3><p class="card-subtitle">${subtitle}</p></div>${extra}</div>`;}
  function lineChart(rows,key,id='main-chart',color='#ff653b',moving=true){
    const read=r=>key==='net'?r.followersGained-r.followersLost:r[key];
    const values=rows.map(read),comparison=previousDays().map(read);
    const averages=rows.map(r=>{const idx=data.daily.findIndex(d=>d.date===r.date);return mean(data.daily.slice(Math.max(0,idx-6),idx+1).map(read));});
    const previous=state.compare&&id==='main-chart'&&comparison.length===rows.length;
    const all=[...values,...(moving?averages:[]),...(previous?comparison:[])],hi=Math.max(...all,1)*1.12,lo=Math.min(0,...all),span=hi-lo||1;
    const x=i=>45+i/(values.length-1||1)*560,y=v=>206-(v-lo)/span*187;
    const path=vals=>vals.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');
    const labels=[0,Math.floor((rows.length-1)*.25),Math.floor((rows.length-1)*.5),Math.floor((rows.length-1)*.75),rows.length-1];
    const names={reach:'alcance',views:'visualizações',net:'saldo de seguidores',followersGained:'novos seguidores',followersLost:'perdas',engagedAccounts:'contas com interação'};
    return `<div class="chart-wrap" id="${id}"><svg class="line-chart" viewBox="0 0 620 235" preserveAspectRatio="none" role="img" aria-label="Evolução diária de ${esc(names[key]||key)}. Valores ao focar cada dia."><defs><linearGradient id="fill-${id}" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="${color}" stop-opacity=".18"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map(i=>{const v=lo+span*i/3;return `<line class="chart-grid" x1="45" x2="605" y1="${y(v)}" y2="${y(v)}"/><text x="35" y="${y(v)+3}" text-anchor="end">${compact(v)}</text>`;}).join('')}${previous?`<path d="${path(comparison)}" fill="none" stroke="#707b90" stroke-width="1.3" stroke-dasharray="3 5" vector-effect="non-scaling-stroke"/>`:''}<path d="${path(values)} L605,206 L45,206 Z" fill="url(#fill-${id})"/><path d="${path(values)}" fill="none" stroke="${color}" stroke-width="2.4" vector-effect="non-scaling-stroke"/>${moving?`<path d="${path(averages)}" fill="none" stroke="#e1ae52" stroke-width="1.5" stroke-dasharray="6 4" vector-effect="non-scaling-stroke"/>`:''}${labels.map(i=>`<text x="${x(i)}" y="227" text-anchor="middle">${shortDate(rows[i].date)}</text>`).join('')}</svg><div class="chart-hits">${rows.map((r,i)=>`<button class="chart-hit" data-tooltip="${shortDate(r.date)} · ${num(values[i])}${moving?` · média 7d: ${num(averages[i])}`:''}${previous?` · anterior: ${num(comparison[i])}`:''}" aria-label="${shortDate(r.date)}: ${num(values[i])}"></button>`).join('')}</div><div class="chart-tooltip"></div></div>`;
  }
  function formatFilter(){return `<label class="format-filter">Formato dos posts <select class="field" id="format-filter"><option value="todos">Todos os formatos</option>${Object.entries(formats).map(([key,label])=>`<option value="${key}" ${state.format===key?'selected':''}>${label}</option>`).join('')}</select></label>`;}
  function postCard(p){return `<article class="card post-card"><div class="post-tile ${p.format}" aria-hidden="true"><span>${p.format==='reel'?'▷':p.format==='carrossel'?'▤':'□'}</span><b>EXEMPLO</b></div><div class="post-description"><div class="post-meta">${shortDate(p.date)} · ${formats[p.format]} · ${p.theme}</div><h4>${postLink(p)}</h4><div class="post-stats"><span><b>${compact(p.views)}</b> views</span><span><b>${decimal(perThousand(p,'shares'))}</b> compart. / mil</span></div></div></article>`;}
  function overview(){
    const d=days(),prev=previousDays(),posts=periodPosts(),top=[...posts].sort((a,b)=>b.views-a.views).slice(0,3);
    const reach=mean(d.map(r=>r.reach)),prevReach=mean(prev.map(r=>r.reach)),engaged=median(d.map(r=>rate(r.engagedAccounts,r.reach))),prevEngaged=median(prev.map(r=>rate(r.engagedAccounts,r.reach)));
    const metricNames={reach:'Alcance',views:'Visualizações',net:'Saldo de seguidores'},values=d.map(r=>state.chartMetric==='net'?r.followersGained-r.followersLost:r[state.chartMetric]);
    const nonFollowers=rate(sum(d,'reachNonFollowers'),sum(d,'reach')),followerShare=100-nonFollowers,gained=sum(d,'followersGained'),lost=sum(d,'followersLost');
    const baseStart=d[0].followersTotal-d[0].followersGained+d[0].followersLost;
    return `<div class="kpi-grid">
    ${kpi('Visualizações',compact(sum(d,'views')),sum(d,'views'),sum(prev,'views'),'◉',d.map(r=>r.views),'Todo o conteúdo da conta')}
    ${kpi('Alcance médio / dia',compact(reach),reach,prevReach,'◎',d.map(r=>r.reach),'Contas únicas em cada dia')}
    ${kpi('Saldo de seguidores',signed(growth(d)),growth(d),growth(prev),'↗',d.map(r=>r.followersGained-r.followersLost),`${pct(rate(growth(d),baseStart))} da base inicial`)}
    ${kpi('Taxa de interação',pct(engaged),engaged,prevEngaged,'♡',d.map(r=>rate(r.engagedAccounts,r.reach)),'Mediana diária · contas / alcance')}
    ${kpi('Visitas ao perfil',compact(sum(d,'profileVisits')),sum(d,'profileVisits'),sum(prev,'profileVisits'),'↗',d.map(r=>r.profileVisits),'Eventos no período')}
    ${kpi('Compartilhamentos',compact(sum(d,'shares')),sum(d,'shares'),sum(prev,'shares'),'⇧',d.map(r=>r.shares),'Eventos no período')}
    ${kpi('Salvamentos',compact(sum(d,'saves')),sum(d,'saves'),sum(prev,'saves'),'▣',d.map(r=>r.saves),'Eventos no período')}
    ${kpi('Cliques externos',compact(sum(d,'externalLinkClicks')),sum(d,'externalLinkClicks'),sum(prev,'externalLinkClicks'),'↗',d.map(r=>r.externalLinkClicks),'Cliques nos links do perfil')}
    </div><div class="grid-2"><article class="card chart-card">
    ${heading(`${metricNames[state.chartMetric]} por dia`,'Evolução da conta · todos os formatos',`<div class="segmented" role="group" aria-label="Métrica do gráfico">${Object.entries(metricNames).map(([key,label])=>`<button data-metric="${key}" aria-pressed="${state.chartMetric===key}">${key==='net'?'Seguidores':label}</button>`).join('')}</div>`)}
    <div class="chart-summary"><strong>${compact(mean(values))}</strong><span>média diária</span><span class="stat-label">Pico: ${compact(Math.max(...values))}</span></div>
    <div class="legend"><span><i></i>Atual</span><span><i class="dashed" style="background:#e1ae52"></i>Média 7d</span>${state.compare?'<span><i class="dashed" style="background:#707b90"></i>Período anterior</span>':''}</div>
    ${lineChart(d,state.chartMetric)}
    <p class="chart-footnote">${state.chartMetric==='reach'?'A mesma conta pode aparecer em vários dias. Este gráfico não mostra alcance único do período.':state.chartMetric==='views'?'Inclui visualizações em publicações antigas.':'Saldo = contas que começaram a seguir − contas que deixaram de seguir.'}${state.compare?' Comparação alinhada pelo dia do período.':''}</p>
    </article><article class="card">${heading('Descoberta e crescimento','Distribuição do alcance diário somado')}
    <div class="acquisition-total">${pct(nonFollowers)}</div><p class="acquisition-caption">do alcance em não seguidores</p>
    <div class="split-bar" role="img" aria-label="${pct(nonFollowers)} não seguidores, ${pct(followerShare)} seguidores"><span style="width:${nonFollowers}%;background:var(--blue)"></span><span style="width:${followerShare}%;background:#7e97db"></span></div>
    <div class="distribution-row"><span><i class="color-dot" style="background:var(--blue)"></i>Não seguidores</span><strong>${pct(nonFollowers)}</strong></div>
    <div class="distribution-row"><span><i class="color-dot" style="background:#7e97db"></i>Seguidores</span><strong>${pct(followerShare)}</strong></div>
    <div class="mini-funnel"><div><span>Começaram a seguir</span><strong>+${num(gained)}</strong></div><div><span>Deixaram de seguir</span><strong class="negative">−${num(lost)}</strong></div><div><span>Saldo líquido</span><strong>${signed(gained-lost)}</strong></div></div>
    <p class="chart-footnote">A proporção pondera o alcance de cada dia; pode contar a mesma pessoa mais de uma vez.</p></article></div>
    <div class="grid-even"><article class="card">${heading('Formato que entrega','Mediana de views aos 7 dias · amostras elegíveis',`<button class="text-button" data-view="conteudo">Comparar →</button>`)}${formatComparison(posts)}</article>
    <article class="card">${heading('Dia × horário','Mediana de views aos 7 dias · fuso de Brasília',`<button class="text-button" data-view="conteudo">Explorar →</button>`)}${heatmap(posts)}</article></div>
    <div class="insight-bar"><span class="insight-icon" aria-hidden="true">↗</span><div><h3>Mais contexto para decidir</h3><p>${posts.length} publicações no período · ${posts.filter(p=>snapshot(p)).length} com leitura de 7 dias · ${pct(rate(lost,baseStart))} de perdas sobre a base inicial. Clique em um post para examinar eficiência, atribuição e snapshots.</p></div></div>
    <div class="section-heading"><h3>Conteúdos em destaque</h3><button class="text-button" data-view="posts">Explorar publicações →</button></div><div class="filters-row">${formatFilter()}<span class="stat-label">Views acumuladas · compart. por mil contas alcançadas</span></div><div class="post-grid">${top.map(postCard).join('')||'<div class="card empty">Nenhuma publicação nesse filtro.</div>'}</div>`;
  }
  function formatComparison(posts){
    const rows=Object.keys(formats).map(key=>({key,values:posts.filter(p=>p.format===key).map(p=>snapshot(p)?.views).filter(Number.isFinite)})),max=Math.max(...rows.map(r=>median(r.values)||0),1);
    return rows.map(r=>`<div class="format-compare"><div class="format-compare-head"><span><i class="color-dot" style="background:${colors[r.key]}"></i>${formats[r.key]}</span><strong>${compact(median(r.values))}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${(median(r.values)||0)/max*100}%;background:${colors[r.key]}"></div></div><div class="format-compare-meta"><span>n=${r.values.length} posts</span><span>Q1–Q3: ${compact(quartile(r.values,.25))}–${compact(quartile(r.values,.75))}</span></div></div>`).join('')+'<p class="chart-footnote">Q1–Q3 contém os 50% centrais da amostra. Uma amostra pequena requer cautela.</p>';
  }
  function heatmap(posts){
    const hours=[6,8,10,12,14,16,18,20,22],week=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];
    const cells=week.flatMap((day,w)=>hours.map(hour=>{const p=posts.filter(p=>new Date(p.date+'T12:00:00Z').getUTCDay()===w&&p.hour===hour&&snapshot(p));return {day,w,hour,posts:p,value:median(p.map(p=>snapshot(p).views))};})),max=Math.max(...cells.map(c=>c.value||0),1);
    return `<div class="heatmap-wrap"><div class="heatmap"><span></span>${hours.map(h=>`<span class="heat-label">${h}h</span>`).join('')}${week.map((day,w)=>`<span class="heat-label">${day}</span>${cells.filter(c=>c.w===w).map(c=>`<button class="heat-cell ${c.posts.length?'':'empty-cell'}" style="background:${c.posts.length?`rgba(255,101,59,${.12+c.value/max*.73})`:'#11141a'}" data-heat-day="${w}" data-heat-hour="${c.hour}" title="${day} ${c.hour}h · ${compact(c.value)} views · n=${c.posts.length}" aria-label="${day}, ${c.hour} horas, ${c.posts.length?`mediana de ${num(c.value)} views em ${c.posts.length} posts`:'sem amostra'}">${c.posts.length?c.posts.length:'·'}</button>`).join('')}`).join('')}</div></div><div class="heatmap-legend"><span>Cada célula mostra o nº de posts</span><span>Menor <i></i> Maior</span></div><div id="heat-selection" class="heat-selection">Clique em uma célula para ver os posts. Células vazias não têm amostra.</div>`;
  }
  function render(){
    if(!views[state.view])state.view='visao';
    const v=views[state.view];$('#view-title').textContent=v.title;$('#view-eyebrow').textContent=v.eyebrow||'DESEMPENHO NO INSTAGRAM';$('#view-subtitle').textContent=v.subtitle;$('#breadcrumb-view').textContent=v.title;
    const icons={visao:'◈',diario:'⌁',conversao:'↗',vida:'◷',conteudo:'▤',reels:'▷',temas:'⌗',publico:'◎',analise:'✧',benchmark:'⇄',posts:'▦',dados:'◇'};
    $('#navigation').innerHTML=Object.entries(views).map(([id,v],i)=>`${i===0?'<div class="nav-group-label">DESEMPENHO</div>':i===4?'<div class="nav-group-label">CONTEÚDO E PÚBLICO</div>':i===8?'<div class="nav-group-label">DECISÕES E DADOS</div>':''}<button class="tab" data-view="${id}" aria-current="${state.view===id?'page':'false'}"><span class="nav-icon" aria-hidden="true">${icons[id]}</span>${v.title}</button>`).join('');
    document.querySelectorAll('[data-range]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.range===String(state.range)));
    $('#compare-period').checked=state.compare;$('#period-label').textContent=`${shortDate(days()[0].date)} — ${shortDate(days().at(-1).date)} · ${state.range} dias`;
    $('#view-content').innerHTML=renderView();
  }
  function bars(items,color='#ff653b',asPercent=false,valuePercent=false){const max=Math.max(...items.map(i=>Number.isFinite(i.value)?i.value:0),1);return `<div class="bar-list">${items.map(i=>`<div><div class="bar-item-head"><span>${esc(i.label)}${i.count!=null?` <span class="stat-label">(${i.count} posts)</span>`:''}</span><strong>${asPercent||valuePercent?pct(i.value):compact(i.value)}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Number.isFinite(i.value)?(asPercent?i.value:i.value/max*100):0}%;background:${i.color||color}"></div></div></div>`).join('')}</div>`;}
  function filteredPosts(){const query=state.query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return periodPosts().filter(p=>(state.theme==='todos'||p.theme===state.theme)&&`${p.title} ${p.theme}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query)).sort((a,b)=>{const av=a[state.sort],bv=b[state.sort];return state.direction*(typeof av==='string'?av.localeCompare(bv):av-bv);});}
  function dailyView(){
    const d=days(),last=d.at(-1),prev=data.daily.slice(-8,-1),base=d[0].followersTotal-d[0].followersGained+d[0].followersLost;
    return `<div class="kpi-grid">${[['reach','Alcance do último dia','◎'],['views','Views do último dia','◉'],['engagedAccounts','Contas com interação','♡'],['followersGained','Novos seguidores','↗']].map(([key,label,icon])=>kpi(label,compact(last[key]),last[key],mean(prev.map(r=>r[key])),icon,d.map(r=>r[key])).replaceAll(`vs. ${state.range} dias anteriores`,'vs. média dos 7 dias anteriores')).join('')}</div><p class="filter-hint">Último dia: ${fullDate(last.date)}. Comparação diária com os 7 dias anteriores, independentemente do período escolhido.</p><div class="grid-even">${[['reach','Alcance da conta','Contas únicas em cada dia'],['views','Visualizações recebidas','Inclui posts antigos'],['followersGained','Novos seguidores','Ganho bruto diário'],['engagedAccounts','Contas com interação','Contas únicas em cada dia']].map(([key,title,sub],i)=>`<article class="card">${heading(title,sub)}<div class="legend"><span><i></i>Por dia</span><span><i class="dashed" style="background:#e1ae52"></i>Média 7d</span></div>${lineChart(d,key,`daily-${i}`)}</article>`).join('')}</div><article class="card">${heading('Crescimento da comunidade','Base inicial, movimento e base final do período')}<div class="coverage-grid">${[['Base inicial',base],['Ganhos brutos',sum(d,'followersGained')],['Perdas',sum(d,'followersLost')],['Saldo líquido',signed(growth(d))],['Base final',last.followersTotal],['Crescimento',pct(rate(growth(d),base))]].map(([label,value])=>`<div class="coverage-stat"><strong>${typeof value==='number'?num(value):value}</strong><span>${label}</span></div>`).join('')}</div><p class="note">Perdas sobre a base inicial: ${pct(rate(sum(d,'followersLost'),base))}. Perdas em relação aos ganhos: ${pct(rate(sum(d,'followersLost'),sum(d,'followersGained')))}. Os denominadores são diferentes.</p>${lineChart(d,'net','daily-net')}</article>`;
  }
  function conversion(){
    const all=periodPosts(),p=all.filter(p=>Number.isFinite(p.profileVisits)&&Number.isFinite(p.attributedFollows)),reach=sum(p,'reach'),visits=sum(p,'profileVisits'),follows=sum(p,'attributedFollows'),rank=[...p].filter(p=>p.reach>=10000).sort((a,b)=>perThousand(b,'attributedFollows')-perThousand(a,'attributedFollows')).slice(0,10),d=days();
    return `<div class="filters-row">${formatFilter()}<span class="pill">Atribuição disponível: ${p.length} / ${all.length} posts</span></div><div class="grid-even"><article class="card">${heading('Descoberta, interesse e ação','Eventos da conta · todos os formatos')}<div class="coverage-grid">${[['Visitas ao perfil',sum(d,'profileVisits')],['Cliques externos',sum(d,'externalLinkClicks')],['Novos seguidores',sum(d,'followersGained')]].map(([label,value])=>`<div class="coverage-stat"><strong>${compact(value)}</strong><span>${label}</span></div>`).join('')}</div>${bars([{label:'Visitas ao perfil',value:sum(d,'profileVisits')},{label:'Cliques externos',value:sum(d,'externalLinkClicks')},{label:'Ganhos de seguidores',value:sum(d,'followersGained')}])}<p class="note">Cliques ÷ visitas: ${pct(rate(sum(d,'externalLinkClicks'),sum(d,'profileVisits')))}. São volumes de eventos, não um percurso individual comprovado.</p></article><article class="card">${heading('Atribuição às publicações',`${p.length} posts cobertos · Reels sem atribuição no exemplo`)}<div class="three-values"><div><strong>${compact(reach)}</strong><span>alcance somado</span></div><div><strong>${compact(visits)}</strong><span>visitas atribuídas</span></div><div><strong>${compact(follows)}</strong><span>seguidores atribuídos</span></div></div><div class="acquisition-total">${decimal(rate(follows,reach,1000))}</div><p class="acquisition-caption">seguidores por mil contas alcançadas</p><p class="note">Visitas e seguidores atribuídos são campos distintos. A razão não mede a conversão individual das visitas; pode haver atribuições sem visita registrada. A mesma conta pode aparecer em vários posts.</p></article></div><div class="section-heading"><h3>Eficiência de aquisição</h3><span class="stat-label">Seguidores por mil alcançados · alcance ≥10 mil</span></div><div class="table-wrap"><table><thead><tr><th>Post</th><th class="numeric">Alcance</th><th class="numeric">Visitas</th><th class="numeric">Seguiram</th><th class="numeric">Seguidores / mil</th></tr></thead><tbody>${rank.map(p=>`<tr><td class="post-title-cell">${postLink(p)}<span class="post-meta">${shortDate(p.date)} · ${formats[p.format]}</span></td><td class="numeric">${num(p.reach)}</td><td class="numeric">${num(p.profileVisits)}</td><td class="numeric">${num(p.attributedFollows)}</td><td class="numeric">${decimal(perThousand(p,'attributedFollows'))}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Sem posts elegíveis com atribuição. Ausência de dado não significa zero.</td></tr>'}</tbody></table></div>`;
  }
  function life(){
    const p=periodPosts(),ages=[1,3,7,30];
    return `<div class="filters-row">${formatFilter()}<span class="stat-label">Snapshots simulados · mesma idade de publicação</span></div><div class="kpi-grid">${ages.map(age=>{const values=p.map(p=>snapshot(p,age)?.views).filter(Number.isFinite);return `<article class="card"><span class="stat-label">${age===1?'24 horas':age+' dias'}</span><div class="kpi-number">${compact(median(values))}</div><span class="stat-label">mediana de views · n=${values.length} / ${p.length}</span><p class="note">Q1–Q3: ${compact(quartile(values,.25))}–${compact(quartile(values,.75))}</p></article>`;}).join('')}</div><p class="note">Cada idade possui uma amostra elegível diferente. Posts recentes não têm snapshot futuro. No filtro de 30 dias, a leitura de 30d pode ficar vazia; amplie o período para incluir posts mais antigos.</p><article class="card">${heading('Comparação aos 7 dias','A idade é controlada; tema e formato ainda variam')}${formatComparison(p)}</article><div class="table-wrap"><table><thead><tr><th>Post</th><th class="numeric">Idade atual</th>${ages.map(age=>`<th class="numeric">${age===1?'24h':age+'d'}</th>`).join('')}</tr></thead><tbody>${[...p].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20).map(p=>`<tr><td class="post-title-cell">${postLink(p)}<span class="post-meta">${shortDate(p.date)} · ${formats[p.format]}</span></td><td class="numeric">${decimal(p.ageDays)}d</td>${ages.map(age=>`<td class="numeric">${compact(snapshot(p,age)?.views)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="6" class="empty">Sem posts nesse filtro.</td></tr>'}</tbody></table></div><p class="note">Tabela: 20 publicações mais recentes. “—” indica idade ainda não atingida. Valores acumulados de cada post estão disponíveis nos detalhes.</p>`;
  }
  function content(){
    const p=periodPosts();
    return `<div class="filters-row">${formatFilter()}<span class="stat-label">${p.length} publicações selecionadas</span></div><div class="grid-even"><article class="card">${heading('Formatos na mesma idade','Views aos 7 dias · mediana e dispersão')}${formatComparison(p)}</article><article class="card">${heading('Eficiência por formato','Mediana de eventos por mil contas alcançadas')}${Object.keys(formats).map(key=>{const rows=p.filter(p=>p.format===key);return `<div class="format-compare"><div class="format-compare-head"><strong>${formats[key]}</strong><span class="stat-label">n=${rows.length}</span></div><div class="format-compare-meta"><span>Compart.: ${decimal(median(rows.map(p=>perThousand(p,'shares'))))}</span><span>Salvos: ${decimal(median(rows.map(p=>perThousand(p,'saves'))))}</span><span>Seguiram: ${decimal(median(rows.map(p=>perThousand(p,'attributedFollows'))))}</span></div></div>`;}).join('')}<p class="chart-footnote">Cada post contribui igualmente à mediana. Seguidores atribuídos ausentes são excluídos, não tratados como zero.</p></article></div><div class="grid-even"><article class="card">${heading('Dias e horários','Mediana de views aos 7 dias · Brasília (UTC−3)')}${heatmap(p)}</article><article class="card">${heading('Distribuição de resultados','Percentual de posts em faixas exclusivas')}${bars([[0,10000,'Menos de 10 mil'],[10000,50000,'10 a 50 mil'],[50000,100000,'50 a 100 mil'],[100000,200000,'100 a 200 mil'],[200000,Infinity,'200 mil ou mais']].map(([min,max,label])=>({label,value:rate(p.filter(p=>p.views>=min&&p.views<max).length,p.length)})),undefined,true)}<p class="chart-footnote">Views acumuladas até a referência. As faixas não se sobrepõem; a idade dos posts pode influenciar a distribuição.</p></article></div><article class="card">${heading('Frequência e volume','Publicações produzidas dentro do período')}<div class="three-values"><div><strong>${p.length}</strong><span>publicações</span></div><div><strong>${decimal(p.length/state.range*7)}</strong><span>posts por semana</span></div><div><strong>${compact(sum(p,'views'))}</strong><span>views acumuladas</span></div></div><p class="chart-footnote">O total desses posts difere das views recebidas pela conta no período, que incluem conteúdo mais antigo.</p></article>`;
  }
  function reels(){
    const p=data.posts.filter(p=>p.date>=days()[0].date&&p.date<=days().at(-1).date&&p.format==='reel'),best=[...p].filter(p=>p.views>=5000).sort((a,b)=>a.skipRate-b.skipRate).slice(0,10);
    return `<p class="filter-hint">${p.length} Reels no período. Esta aba considera Reels independentemente do filtro de formato.</p><div class="retention-grid">${[['Taxa mediana de pulo',pct(median(p.map(p=>p.skipRate))),'Pessoas que passaram adiante no início'],['Mediana do tempo assistido',decimal(median(p.map(p=>p.averageWatchSeconds)))+'s','Mediana dos tempos médios de cada Reel'],['Mediana da proporção assistida',pct(median(p.map(p=>rate(p.averageWatchSeconds,p.durationSeconds)))),'Tempo médio assistido ÷ duração']].map(([label,val,sub])=>`<article class="card retention-kpi">${heading(label,sub)}<div class="big-value">${val}</div><span class="stat-label">n=${p.length} Reels demonstrativos</span></article>`).join('')}</div><div class="grid-even"><article class="card">${heading('Duração × proporção assistida','Clique em um ponto para abrir a publicação')}${scatter(p)}<p class="chart-footnote">Cada ponto é um Reel. Tamanho = views; laranja = pulo abaixo de 40%. Associação não prova causalidade.</p></article><article class="card">${heading('Duração e alcance','Mediana de views acumuladas por faixa')}${bars([[0,30,'Até 30s'],[31,60,'31 a 60s'],[61,90,'61 a 90s'],[91,Infinity,'Mais de 90s']].map(([min,max,label])=>{const rows=p.filter(p=>p.durationSeconds>=min&&p.durationSeconds<=max);return {label,value:median(rows.map(p=>p.views)),count:rows.length};}))}<p class="chart-footnote">A duração é uma variável entre várias. Compare também tema, idade, retenção e tamanho da amostra.</p></article></div><div class="section-heading"><h3>Retenção em detalhe</h3><span class="stat-label">Menor pulo · mínimo de 5 mil views</span></div><div class="table-wrap"><table><thead><tr><th>Reel</th><th class="numeric">Views</th><th class="numeric">Pulo</th><th class="numeric">Assistido</th><th class="numeric">Duração</th><th class="numeric">Compart. / mil</th></tr></thead><tbody>${best.map(p=>`<tr><td class="post-title-cell">${postLink(p)}<div class="post-meta">${shortDate(p.date)} · ${p.theme}</div></td><td class="numeric">${num(p.views)}</td><td class="numeric">${pct(p.skipRate)}</td><td class="numeric">${p.averageWatchSeconds}s</td><td class="numeric">${p.durationSeconds}s</td><td class="numeric">${decimal(perThousand(p,'shares'))}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Sem Reels elegíveis.</td></tr>'}</tbody></table></div>`;
  }
  function scatter(posts){
    const max=Math.max(...posts.map(p=>p.views),1),x=v=>45+v/100*550,y=v=>235-v/100*215;
    return `<svg class="scatter-chart" viewBox="0 0 620 275" role="img" aria-label="Duração em segundos no eixo horizontal e proporção assistida no vertical">${[0,25,50,75,100].map(v=>`<line class="chart-grid" x1="45" x2="595" y1="${y(v)}" y2="${y(v)}"/><text x="36" y="${y(v)+4}" text-anchor="end">${v}%</text><text x="${x(v)}" y="255" text-anchor="middle">${v}s</text>`).join('')}${posts.map(p=>`<circle class="scatter-point" cx="${x(p.durationSeconds)}" cy="${y(rate(p.averageWatchSeconds,p.durationSeconds))}" r="${4+Math.sqrt(p.views/max)*10}" fill="${p.skipRate<40?'#ff653b':'#7e97db'}" fill-opacity=".7" stroke="${p.skipRate<40?'#ff986e':'#a6b9ed'}" stroke-width="1" tabindex="0" role="button" data-post="${p.id}" aria-label="${esc(p.title)}: ${p.durationSeconds}s, ${pct(rate(p.averageWatchSeconds,p.durationSeconds))} assistido"><title>${esc(p.title)} · ${compact(p.views)} views · pulo ${pct(p.skipRate)}</title></circle>`).join('')}</svg>`;
  }
  function themesView(){
    const p=periodPosts(),themes=[...new Set(data.posts.map(p=>p.theme))],rows=themes.map(theme=>{const posts=p.filter(p=>p.theme===theme);return {label:theme,value:median(posts.map(p=>snapshot(p)?.views)),count:posts.filter(p=>snapshot(p)).length,posts};});
    return `<div class="filters-row">${formatFilter()}<span class="stat-label">Classificação editorial demonstrativa</span></div><div class="grid-even"><article class="card">${heading('Views por tema','Mediana de views aos 7 dias')}${bars(rows)}<p class="chart-footnote">Somente snapshots de 7d disponíveis. O nº de posts em cada barra indica a amostra elegível.</p></article><article class="card">${heading('Potencial de distribuição','Mediana de compartilhamentos por mil alcançados')}${bars(rows.map(r=>({label:r.label,value:median(r.posts.map(p=>perThousand(p,'shares'))),count:r.posts.length})))}<p class="chart-footnote">Eventos acumulados ÷ alcance × 1.000. Uma taxa alta em poucos posts pode não se repetir.</p></article></div><div class="section-heading"><h3>Tema × formato</h3><span class="stat-label">Mediana de views aos 7 dias / nº de posts</span></div><div class="table-wrap"><table><thead><tr><th>Tema</th>${Object.values(formats).map(f=>`<th class="numeric">${f}</th>`).join('')}</tr></thead><tbody>${themes.map(theme=>`<tr><td><strong>${theme}</strong></td>${Object.keys(formats).map(key=>{const rows=p.filter(p=>p.theme===theme&&p.format===key&&snapshot(p));return `<td class="numeric">${compact(median(rows.map(p=>snapshot(p).views)))}<div class="post-meta">n=${rows.length}</div></td>`;}).join('')}</tr>`).join('')}</tbody></table></div><p class="note">A matriz ajuda a distinguir tema de formato. Posts de cada grupo ainda podem diferir em objetivo, horário e público; estes números são fictícios.</p>`;
  }
  function audience(){return `<div class="insight-bar"><span class="insight-icon" aria-hidden="true">◎</span><div><h3>Retrato demonstrativo dos seguidores</h3><p>As distribuições abaixo são fictícias e fixas na data do exemplo. O filtro de período não altera este retrato; seguidores não representam todo o público alcançado.</p></div></div><div class="grid-3">${[['Faixa etária','Distribuição dos seguidores','age'],['Gênero','Distribuição dos seguidores','gender'],['Cidades','Distribuição dos seguidores','cities']].map(([title,sub,key],i)=>`<article class="card">${heading(title,sub,`<span class="small-tag">Exemplo fixo</span>`)}${bars(data.audience[key],i===1?'#399480':i===2?'#b79869':undefined,true)}</article>`).join('')}</div><p class="note">Não há conexão com o Instagram. Idade, gênero e localização não foram coletados do seu perfil.</p>`;}
  function analysis(){const p=periodPosts(),stats=Object.keys(formats).map(key=>{const rows=p.filter(p=>p.format===key);return {key,count:rows.length,value:median(rows.map(p=>p.views)),saves:median(rows.map(p=>p.saves/p.views*100))};}).filter(r=>r.count).sort((a,b)=>b.value-a.value),best=stats[0],saves=[...stats].sort((a,b)=>b.saves-a.saves)[0];const advice=[['Compare o centro da amostra',best?`${formats[best.key]} têm mediana de ${compact(best.value)} views em ${best.count} posts neste exemplo. Compare também a amostra e a idade dos posts.`:'Sem posts nesse filtro.'],['Observe o conteúdo de consulta',saves?`${formats[saves.key]} têm a maior mediana de salvamentos ÷ views: ${pct(saves.saves)} no exemplo. Em dados reais, teste se conteúdos de referência repetem esse comportamento.`:'Sem posts nesse filtro.'],['Separe alcance de conversão','Visitas e seguidores atribuídos ajudam a entender a conversão quando disponíveis. Um viral com muitas views pode trazer poucos seguidores.']];return `<div class="filters-row">${formatFilter()}<span class="stat-label">Leitura calculada sobre dados fictícios</span></div><div class="grid-3">${advice.map(([title,body],i)=>`<article class="card advice"><span class="advice-number">0${i+1}</span><div><h3>${title}</h3><p>${body}</p></div></article>`).join('')}</div><div class="insight-bar"><span class="insight-icon" aria-hidden="true">✧</span><div><h3>Um ponto de partida, sem receita pronta</h3><p>Estas leituras demonstram o painel. Para recomendar uma estratégia para @47contadoallan, precisamos dos resultados reais e dos objetivos do perfil.</p></div></div><div class="section-heading"><h3>Semana modelo</h3><span class="stat-label">Exemplo editorial para adaptar</span></div><article class="card"><div class="calendar-grid">${[['SEG','Resumo de atualidades','Carrossel'],['TER','Uma pergunta e sua análise','Reel'],['QUA','Bastidores da transmissão','Imagem'],['QUI','Resposta a uma dúvida','Reel'],['SEX','A semana em cinco fatos','Carrossel'],['SÁB','Conversa com a comunidade','Stories'],['DOM','Revisão e planejamento','Stories']].map(([day,title,format])=>`<div class="calendar-day"><h4>${day}</h4><p>${title}</p><span>${format}</span></div>`).join('')}</div><p class="chart-footnote">Calendário ilustrativo. Não agenda nem publica conteúdos; ajuste temas, frequência e horários com base na sua rotina e nos dados reais.</p></article>`;}
  function benchmark(){const p=periodPosts();return `<div class="filters-row">${formatFilter()}<span class="stat-label">Referências externas ainda não configuradas</span></div><div class="table-wrap"><table><thead><tr><th>Métrica e fórmula</th><th class="numeric">Seu exemplo</th><th>Referência</th><th>Fonte e período</th></tr></thead><tbody>${[['Engajamento por post','(curtidas + comentários + compartilhamentos + salvos) ÷ seguidores',p.length?pct(median(p.map(p=>(p.likes+p.comments+p.shares+p.saves)/data.profile.followers*100))):'sem dado'],['Taxa de compartilhamento','compartilhamentos ÷ views',p.length?pct(median(p.map(p=>p.shares/p.views*100))):'sem dado'],['Views por post','mediana das publicações do período',p.length?compact(median(p.map(p=>p.views))):'sem dado'],['Frequência','posts publicados ÷ dias × 7',(p.length/state.range*7).toLocaleString('pt-BR',{maximumFractionDigits:1})+' / semana']].map(([label,formula,value])=>`<tr><td><strong>${label}</strong><div class="post-meta">${formula}</div></td><td class="numeric">${value}</td><td class="stat-label">sem dado</td><td class="stat-label">A definir</td></tr>`).join('')}</tbody></table></div><p class="note">Nenhuma média de mercado foi inventada. Para preencher a comparação, escolha uma fonte verificável, uma conta de tamanho e segmento semelhantes e a mesma fórmula. Esta coluna do exemplo usa mediana; não compare diretamente com média sem registrar a diferença.</p>`;}
  function postsView(){
    const p=filteredPosts(),size=12,maxPage=Math.max(0,Math.ceil(p.length/size)-1);state.page=Math.min(state.page,maxPage);
    const shown=p.slice(state.page*size,(state.page+1)*size),headers=[['date','Data'],['title','Post'],['views','Views'],['reach','Alcance'],['likes','Curtidas'],['comments','Coment.'],['shares','Compart.'],['saves','Salvos']];
    return `<div class="filters-row"><input type="search" class="field search" id="post-search" placeholder="Buscar título ou tema…" aria-label="Buscar posts" value="${esc(state.query)}">${formatFilter()}<select class="field" id="theme-filter" aria-label="Filtrar posts por tema"><option value="todos">Todos os temas</option>${[...new Set(data.posts.map(p=>p.theme))].map(t=>`<option ${state.theme===t?'selected':''}>${esc(t)}</option>`).join('')}</select><button class="button primary" id="export-csv">Baixar CSV (${p.length})</button></div><div class="table-wrap"><table><thead><tr>${headers.map(([key,label],i)=>`<th class="${i>1?'numeric':''}" aria-sort="${state.sort===key?(state.direction===1?'ascending':'descending'):'none'}"><button class="sort-button" data-sort="${key}">${label}${state.sort===key?(state.direction===1?' ↑':' ↓'):''}</button></th>`).join('')}<th class="numeric">Compart. / mil</th><th class="numeric">Seguiram / mil</th></tr></thead><tbody>${shown.map(p=>`<tr><td style="white-space:nowrap">${shortDate(p.date)}<div class="post-meta">${p.hour}h · UTC−3</div></td><td class="post-title-cell">${postLink(p)}<div><span class="format-badge ${p.format}">${formats[p.format]}</span> <span class="post-meta">${p.theme} · ${p.objective}</span></div></td>${['views','reach','likes','comments','shares','saves'].map(key=>`<td class="numeric">${num(p[key])}</td>`).join('')}<td class="numeric">${decimal(perThousand(p,'shares'))}</td><td class="numeric">${decimal(perThousand(p,'attributedFollows'))}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">Nenhum post encontrado. Experimente outro título, tema ou formato.</td></tr>'}</tbody></table></div><div class="pagination"><span>${p.length?`${state.page*size+1}–${Math.min((state.page+1)*size,p.length)} de ${p.length} posts`:'0 posts'} · dados fictícios</span><div class="pagination-controls"><button class="button" data-page="-1" ${state.page===0?'disabled':''}>Anterior</button><button class="button" data-page="1" ${state.page>=maxPage?'disabled':''}>Próxima</button></div></div><p class="note">Clique no título para abrir detalhes. “/ mil” usa o alcance do post como denominador. O CSV inclui todos os filtros e snapshots, independentemente da página.</p>`;
  }
  function exportCSV(){
    const p=filteredPosts(),headers=['modo','id','data','publicado_em','fuso','idade_dias','referencia_em','titulo','formato','tema','objetivo','views','alcance','curtidas','comentarios','compartilhamentos','salvos','visitas_perfil','seguidores_atribuidos','compart_por_mil_alcancados','salvos_por_mil_alcancados','seguidores_por_mil_alcancados','duracao_s','assistido_s','taxa_pulo_pct','views_24h','views_3d','views_7d','views_30d','cobertura_atribuicao'];
    const rows=p.map(p=>['demonstracao',p.id,p.date,p.publishedAt,data.meta.timezone,p.ageDays.toFixed(2),data.meta.collectedAt,p.title,p.format,p.theme,p.objective,p.views,p.reach,p.likes,p.comments,p.shares,p.saves,p.profileVisits??'',p.attributedFollows??'',perThousand(p,'shares')??'',perThousand(p,'saves')??'',perThousand(p,'attributedFollows')??'',p.durationSeconds??'',p.averageWatchSeconds??'',p.skipRate??'',...[1,3,7,30].map(age=>snapshot(p,age)?.views??''),p.attributedFollows==null?'ausente':'disponivel']);
    const csv='\uFEFF'+[headers,...rows].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');
    const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'})),a=document.createElement('a');a.href=url;a.download=`47contadoallan-demonstracao-${state.range}dias.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify(`${p.length} posts demonstrativos exportados.`);
  }
  function dataView(){
    const p=periodPosts(),covered=p.filter(p=>Number.isFinite(p.attributedFollows)),valid7=p.filter(p=>snapshot(p)),allFields=[['Métricas da conta','360 dias · todos os formatos','Simulação local','Diária'],['Publicações',`${p.length} posts no filtro`,'Simulação local','Acumulada por post'],['Visitas / seguidores atribuídos',`${covered.length} / ${p.length} posts`,'Ausentes nos Reels','Acumulada por post'],['Snapshots de 7 dias',`${valid7.length} / ${p.length} posts`,'Simulação por idade','24h, 3d, 7d, 30d'],['Público','Retrato fixo','Simulação local','Não varia por período'],['Benchmark externo','Sem fonte','Ainda não configurado','Sem dado']];
    return `<article class="card">${heading('Origem e qualidade','Nenhuma métrica foi coletada do Instagram')}<div class="coverage-grid"><div class="coverage-stat"><strong>${data.daily.length}</strong><span>dias demonstrativos</span></div><div class="coverage-stat"><strong>${data.posts.length}</strong><span>publicações fictícias</span></div><div class="coverage-stat"><strong>${pct(rate(covered.length,p.length))}</strong><span>atribuição no filtro</span></div></div><p class="note">Gerador local determinístico · versão ${data.meta.version} · referência em UTC: ${data.meta.collectedAt} (20:59:59 de 06/10/2026 em Brasília) · publicações: ${data.meta.timezone}.</p><button class="button primary" id="export-json">Baixar estrutura demonstrativa (JSON)</button></article><div class="table-wrap"><table class="source-table"><thead><tr><th>Conjunto</th><th>Cobertura</th><th>Fonte / ausência</th><th>Granularidade</th></tr></thead><tbody>${allFields.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="grid-even"><article class="card">${heading('Fórmulas abertas','Cada indicador declara seu denominador')}<div class="insight-list">${[['Alcance médio diário','Soma do alcance diário ÷ dias. Não equivale a alcance único do período.'],['Taxa de interação','Mediana de contas com interação ÷ alcance em cada dia × 100.'],['Crescimento da base','Saldo líquido ÷ base inicial × 100.'],['Eficiência por post','Compartilhamentos, salvos ou seguidores atribuídos ÷ alcance × 1.000.'],['Comparação de períodos','(Atual − anterior) ÷ valor absoluto anterior × 100.']].map(([title,body])=>`<div class="insight-item"><strong>${title}</strong><p>${body}</p></div>`).join('')}</div></article><article class="card">${heading('Preparação para dados reais','Estrutura disponível para uma futura integração')}<div class="insight-list"><div class="insight-item"><strong>Campos ausentes</strong><p>Use null para ausência. O painel mostra “—” e exclui nulos de medianas e taxas. Totais da demonstração usam campos diários completos; uma importação real precisa validar também a cobertura dos totais.</p></div><div class="insight-item"><strong>Snapshots e referência</strong><p>Registre o horário da coleta e a idade do post para comparar resultados nas mesmas janelas.</p></div><div class="insight-item"><strong>Identificação e fonte</strong><p>IDs, data, fuso, objetivo, formato, tema e cobertura acompanham as exportações.</p></div><div class="insight-item"><strong>Próximo passo</strong><p>Substituir o exemplo por uma exportação validada ou integração autorizada. Esta versão não autentica nem consulta o Instagram.</p></div></div></article></div>`;
  }
  function renderView(){return ({visao:overview,diario:dailyView,conversao:conversion,vida:life,conteudo:content,reels,temas:themesView,publico:audience,analise:analysis,benchmark,posts:postsView,dados:dataView})[state.view]();}
  function navigate(view){if(!views[view])return;state.view=view;state.page=0;history.replaceState(null,'','#'+view);render();$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');$('#main').scrollIntoView({behavior:'smooth',block:'start'});}
  function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
  document.addEventListener('click',e=>{const view=e.target.closest('[data-view]'),range=e.target.closest('[data-range]'),metric=e.target.closest('[data-metric]'),sort=e.target.closest('[data-sort]'),page=e.target.closest('[data-page]');if(view)navigate(view.dataset.view);if(range){state.range=Number(range.dataset.range);state.page=0;render();}if(metric){state.chartMetric=metric.dataset.metric;render();}if(sort){if(state.sort===sort.dataset.sort)state.direction*=-1;else {state.sort=sort.dataset.sort;state.direction=-1;}state.page=0;render();}if(page&&!page.disabled){state.page+=Number(page.dataset.page);render();}if(e.target.closest('#export-csv'))exportCSV();const post=e.target.closest('[data-post]');if(post)showPost(post.dataset.post);const heat=e.target.closest('[data-heat-day]');if(heat){const posts=periodPosts().filter(p=>new Date(p.date+'T12:00:00Z').getUTCDay()===Number(heat.dataset.heatDay)&&p.hour===Number(heat.dataset.heatHour)&&snapshot(p));$('#heat-selection').innerHTML=posts.length?`${posts.length} posts · mediana ${compact(median(posts.map(p=>snapshot(p).views)))} views aos 7 dias. ${posts.map(postLink).join(' · ')}`:'Sem posts com snapshot de 7 dias neste horário.';}if(e.target.closest('#close-post'))$('#post-dialog').close();if(e.target.closest('#export-json'))downloadJSON();});
  document.addEventListener('change',e=>{if(e.target.id==='compare-period'){state.compare=e.target.checked;render();}if(e.target.id==='format-filter'){state.format=e.target.value;state.page=0;render();}if(e.target.id==='theme-filter'){state.theme=e.target.value;state.page=0;render();}});
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.scatter-point')){e.preventDefault();showPost(e.target.dataset.post);}});
  document.addEventListener('input',e=>{if(e.target.id==='post-search'){state.query=e.target.value;state.page=0;const focus=e.target,position=focus.selectionStart;render();const input=$('#post-search');input.focus();try{input.setSelectionRange(position,position);}catch{}}});
  function showTooltip(e){const hit=e.target.closest('.chart-hit');if(!hit)return;const wrap=hit.closest('.chart-wrap'),tip=wrap.querySelector('.chart-tooltip');tip.textContent=hit.dataset.tooltip;tip.style.display='block';}
  document.addEventListener('mouseover',showTooltip);document.addEventListener('focusin',showTooltip);
  document.addEventListener('mouseout',e=>{if(e.target.closest('.chart-hit'))e.target.closest('.chart-wrap').querySelector('.chart-tooltip').style.display='none';});document.addEventListener('focusout',e=>{if(e.target.closest('.chart-hit'))e.target.closest('.chart-wrap').querySelector('.chart-tooltip').style.display='none';});
  function showPost(id){
    const p=data.posts.find(p=>p.id===id);if(!p)return;
    const metrics=[['Views acumuladas',p.views],['Contas alcançadas',p.reach],['Curtidas',p.likes],['Comentários',p.comments],['Compartilhamentos',p.shares],['Salvamentos',p.saves],['Visitas ao perfil',p.profileVisits],['Seguidores atribuídos',p.attributedFollows]];
    $('#post-detail-content').innerHTML=`<div class="dialog-head"><span class="small-tag">PUBLICAÇÃO DEMONSTRATIVA</span><button class="icon-button" id="close-post" aria-label="Fechar detalhes">×</button></div><div class="detail-header"><h2 id="post-detail-title">${esc(p.title)}</h2><div class="detail-meta">${fullDate(p.date)} · ${p.hour}h · Brasília (UTC−3) · ${formats[p.format]} · ${p.theme}</div><p class="stat-label">Objetivo: ${p.objective} · Idade: ${decimal(p.ageDays)} dias · ID: ${p.id}</p></div><div class="detail-grid">${metrics.map(([label,value])=>`<div class="detail-metric"><span>${label}</span><strong>${num(value)}</strong></div>`).join('')}</div><div class="grid-even"><div><h3>Eficiência por mil alcançados</h3>${bars(['shares','saves','attributedFollows'].map((key,i)=>({label:['Compartilhamentos','Salvamentos','Seguidores atribuídos'][i],value:perThousand(p,key)})))}<p class="chart-footnote">Campo ÷ alcance × 1.000. Seguidores: ${p.attributedFollows==null?'sem dado':decimal(perThousand(p,'attributedFollows'))}.</p></div><div><h3>Views na mesma idade</h3><div class="detail-snapshots">${[1,3,7,30].map(age=>{const snap=snapshot(p,age);return `<div class="snapshot ${snap?'':'missing'}"><span>${age===1?'24h':age+'d'}</span><strong>${snap?compact(snap.views):'—'}</strong><span>${snap?'snapshot simulado':'idade não atingida'}</span></div>`;}).join('')}</div></div></div>${p.format==='reel'?`<p class="note">Duração: ${p.durationSeconds}s · Tempo médio assistido: ${p.averageWatchSeconds}s · Proporção assistida: ${pct(rate(p.averageWatchSeconds,p.durationSeconds))} · Pulo: ${pct(p.skipRate)}.</p>`:''}<p class="note">Sem publicação real vinculada. Valores fictícios acumulados até ${fullDate(data.meta.referenceDate)}; um traço indica ausência de dado.</p>`;
    $('#post-dialog').showModal();
  }
  function downloadJSON(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='47contadoallan-demonstracao-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Estrutura demonstrativa exportada.');}
  $('#menu-toggle').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open));});
  $('#open-data-view').addEventListener('click',()=>{$('#info-dialog').close();navigate('dados');});
  $('#data-info').addEventListener('click',()=>$('#info-dialog').showModal());$('#close-info').addEventListener('click',()=>$('#info-dialog').close());$('#info-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}});
  $('#hero-followers').textContent=num(data.profile.followers);$('#hero-growth').textContent=signed(growth(data.daily.slice(-30)));$('#hero-posts').textContent=num(data.posts.filter(p=>p.date>=data.daily.at(-30).date).length);
  const initialView=location.hash.slice(1);if(views[initialView])state.view=initialView;
  window.addEventListener('hashchange',()=>{const view=location.hash.slice(1);if(views[view]){state.view=view;render();}});
  render();
  const context=document.modelContext;
  if(context?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
    register({name:'read_instagram_demo_dashboard',title:'Ler painel demonstrativo',description:'Lê os filtros e indicadores do exemplo fictício de @47contadoallan. Não consulta o Instagram.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({mode:'demo',profile:data.profile.handle,view:state.view,range:state.range,format:state.format,views:sum(days(),'views'),averageDailyReach:Math.round(mean(days().map(d=>d.reach))),netFollowers:growth(days()),filteredPostCount:filteredPosts().length})});
    register({name:'configure_instagram_demo_dashboard',title:'Configurar filtros do exemplo',description:'Atualiza a aba, o período e o formato dos posts no painel demonstrativo visível. Não modifica dados nem publica conteúdos.',inputSchema:{type:'object',properties:{view:{type:'string',enum:Object.keys(views)},range:{type:'integer',enum:[7,30,60,90,180]},format:{type:'string',enum:['todos','reel','imagem','carrossel']}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['view','range','format'].includes(k))||('view'in input&&!views[input.view])||('range'in input&&![7,30,60,90,180].includes(input.range))||('format'in input&&!['todos','reel','imagem','carrossel'].includes(input.format)))throw new Error('Filtros inválidos.');Object.assign(state,input,{page:0});history.replaceState(null,'','#'+state.view);render();return {mode:'demo',view:state.view,range:state.range,format:state.format};}});
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
